import { Blocks, Smile } from "lucide-react";
import psychiatricIcon from "@assets/generated_images/psychiatric_evaluations_icon.png";
import psychotherapyIcon from "@assets/generated_images/psychotherapy_icon.png";
import medicationIcon from "@assets/generated_images/medication_management_icon.png";
import childTherapyIcon from "@assets/generated_images/child_adolescent_therapy_icon.png";
import spravatoIcon from "@assets/generated_images/spravato_treatment_icon.png";
import tmsIcon from "@assets/generated_images/tms_therapy_icon.png";
import couplesIcon from "@assets/generated_images/couples_therapy_icon.png";
import groupTherapyIcon from "@assets/generated_images/group_therapy_icon.png";
import dbtIcon from "@assets/generated_images/dbt_skill_therapy_icon.png";
import schemaIcon from "@assets/generated_images/schema_therapy_icon.png";

export const services = [
  {
    id: "psychiatric-evaluations",
    title: "Psychiatric Evaluations",
    description: "Comprehensive assessments to diagnose behavioral health conditions and create tailored treatment plans.",
    iconImage: psychiatricIcon,
  },
  {
    id: "psychotherapy",
    title: "Psychotherapy",
    description: "Talk therapy to explore thoughts and feelings, develop coping skills, and improve behavioral well-being.",
    iconImage: psychotherapyIcon,
  },
  {
    id: "medication-management",
    title: "Medication Management",
    description: "Prescribing and monitoring medications to treat behavioral health conditions, adjusting as needed for effectiveness.",
    iconImage: medicationIcon,
  },
  {
    id: "child-adolescent-therapy",
    title: "Child/Adolescent Therapy",
    description: "Specialized therapy for young people to address emotional and behavioral issues through age-appropriate techniques.",
    iconImage: childTherapyIcon,
  },
  {
    id: "spravato",
    title: "Spravato",
    description: "Esketamine, a cutting-edge medication for severe depression, used alongside oral antidepressants, requiring medical supervision.",
    iconImage: spravatoIcon,
  },
  {
    id: "tms",
    title: "TMS",
    description: "Non-invasive, state-of-the-art treatment using magnetic fields to stimulate brain cells, helping alleviate depression or OCD.",
    iconImage: tmsIcon,
  },
  {
    id: "couples-therapy",
    title: "Couples Therapy",
    description: "Guided sessions to improve communication, resolve conflicts, and strengthen relationships.",
    iconImage: couplesIcon,
  },
  {
    id: "group-therapy",
    title: "Group Therapy",
    description: "Therapy with a small group to provide support, share experiences, and gain diverse perspectives on similar issues.",
    iconImage: groupTherapyIcon,
  },
  {
    id: "dbt-skill-therapy",
    title: "DBT Skill Therapy",
    description: "Long-term weekly program focused on mindfulness, emotion regulation, distress tolerance, and interpersonal effectiveness.",
    iconImage: dbtIcon,
  },
  {
    id: "schema-therapy",
    title: "Schema Therapy",
    description: "Long-term weekly program focused on deep inner work to address core unmet emotional needs.",
    iconImage: schemaIcon,
  },
  {
    id: "play-therapy",
    title: "Play Therapy",
    description: "Therapeutic approach using play to help children express feelings, resolve conflicts, and develop coping skills.",
    icon: Blocks,
  },
  {
    id: "general-wellness",
    title: "General Wellness",
    description: "Holistic approach to mental health focusing on overall well-being, stress management, and healthy lifestyle habits.",
    icon: Smile,
  },
];

export const locations = [
  {
    name: "Jamestown, NY",
    address: "1465 Foote Avenue",
    city: "Jamestown, NY 14701",
    phone: "+1 (716) 526-4041",
    fax: "+1 (716) 526-4161",
  },
  {
    name: "Olean, NY",
    address: "237 Delaware Ave",
    city: "Olean, NY 14760",
    phone: "+1 (716) 790-8847",
  },
  {
    name: "Ridgway, PA",
    address: "20 Gillis Ave",
    city: "Ridgway, PA 15853",
    phone: "+1 (814) 772-5741",
  },
];

export const faqs = [
  {
    question: "What can I expect from Spravato?",
    answer: "SPRAVATO® is taken with an oral antidepressant. You administer SPRAVATO® nasal spray yourself under the supervision of a healthcare provider at a certified SPRAVATO® treatment center. SPRAVATO® is taken twice a week for the first four weeks. After the first four weeks, you and your doctor will discuss and determine if treatment should be continued and the dose and how often you'll receive SPRAVATO®.",
  },
  {
    question: "What is Deep Transcranial Magnetic Stimulation (Deep TMS™)?",
    answer: "Deep transcranial magnetic stimulation (Deep TMS™), is a noninvasive treatment process that directly stimulates brain structures associated with behavioral health conditions. This is done utilizing electromagnetic fields generated by our patented H-coil to safely reach deeper brain structures and influence their neural activity. Deep TMS treatment has been proven to offer significant results by directly stimulating deeper and broader areas of the brain, effectively treating conditions such as depression, anxious depression, late-life depression, obsessive-compulsive disorder, and smoking addiction.",
  },
  {
    question: "What are the benefits of Tele-health?",
    answer: "Telepsychiatry offers numerous advantages, particularly in expanding access to behavioral health care for individuals in remote or underserved areas. It eliminates the need for travel, reducing time and costs, and provides patients with greater flexibility in scheduling appointments. This is especially beneficial for those with mobility issues or busy lifestyles. Telepsychiatry can enhance continuity of care by facilitating more frequent check-ins and medication management. Patients often feel more comfortable in their own environment, which can improve the quality of sessions. Additionally, it helps bridge the gap in behavioral health professional shortages, ensuring timely care for more people.",
  },
  {
    question: "Do you offer in-person appointments?",
    answer: "Yes, we offer in person appointments at any one of our three locations. If you prefer to be seen in person, please note that there may be a longer wait due to more limited availability in our physical office. Booking an appointment via telehealth allows us to see you much sooner, offering quicker access to care and the flexibility to meet from the comfort of your own home. With telehealth, we can often accommodate appointments more rapidly than in-person visits.",
  },
  {
    question: "What insurance do you accept?",
    answer: "We accept most major insurance providers including Aetna, Cigna, United Healthcare, Blue Cross Blue Shield, and Humana. We recommend contacting our office to verify that your specific plan is accepted and to understand your coverage details.",
  },
  {
    question: "How long is the first appointment?",
    answer: "Initial psychiatric evaluations typically last 60-90 minutes. This comprehensive assessment allows our providers to understand your needs, medical history, and create a personalized treatment plan. Follow-up appointments are usually 30-60 minutes depending on the type of service.",
  },
];
